export type { Terminal, TerminalStatus } from './terminal';
export type { TerminalConfiguration } from './terminal-configuration';
export { createDefaultTerminalConfiguration } from './terminal-configuration';
export type { DeviceRegistration, DeviceRegistrationStatus } from './device-registration';
export type { CreateTerminalInput, UpdateTerminalInput } from './validation/terminal-validation';
export { validateCreateTerminal, validateUpdateTerminal } from './validation/terminal-validation';
export type { RegisterDeviceInput } from './validation/device-registration-validation';
export { validateRegisterDevice } from './validation/device-registration-validation';
export { suspendTerminal, reactivateTerminal } from './lifecycle/terminal-lifecycle';
export { revokeDevice, deactivateDevice } from './lifecycle/device-registration-lifecycle';
export type { TerminalRepository } from './repositories/terminal-repository';
export type { DeviceRegistrationRepository } from './repositories/device-registration-repository';
